### ISSUE TITLE
Android Availability?

### ISSUE THREAD

**Issue by imurreflection** [j-holub/Node-MPV#67]
Hi, is this awesome application available on Android mate?

**Comment by j-holub** [comment]
Hey there, 

this is a package for NPM/NodeJs, what do you mean by available on Android?

Is there a NodeJs environment for Android? And even if, I don’t think it will work because it requires to start mpv player as a process and open a network socket.

What would you want to do with it on Android?

**Comment by j-holub** [comment]
Closing this for because of a lack of information. Feel free to reopen if needed.

**Comment by Utopiah** [comment]
> Is there a NodeJs environment for Android? And even if, I don’t think it will work because it requires to start mpv player as a process and open a network socket.

Yes, for example I use Termux on Meta Quest (XR headset) and install NodeJS on it, cf https://wiki.termux.com/index.php?title=Node.js

I'd be curious to know if it's possible but I would indeed be wondering how processes could communicate with each other. I believe on Android that's usually done with intents rather than IPC so this might require additional work.
